# Generated by build/homebrew/render-formula.sh when a release is published;
# edit the template in chapar-rest/chapar, not this file.
class ChaparCli < Formula
  desc "Run Chapar API test cases from the command-line"
  homepage "https://github.com/chapar-rest/chapar"
  version "0.9.0"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.0/chapar-cli-macos-v0.9.0-arm64.tar.gz"
      sha256 "764e779ff5760e9620bd429e2fbe29ceeb6d8342af1e61da2b9f50edb869b579"
    end
    on_intel do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.0/chapar-cli-macos-v0.9.0-amd64.tar.gz"
      sha256 "bafb7f92373cae07fcc75ce06cd577f38d05edb8132c03a5386fe50ea406ae43"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.0/chapar-cli-linux-v0.9.0-arm64.tar.gz"
      sha256 "c703bd6dbe284b1952632bbedd4591eb31211b9340266e283c18381ada871f44"
    end
    on_intel do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.0/chapar-cli-linux-v0.9.0-amd64.tar.gz"
      sha256 "921290b3469f8f70b742a50d3603122ea7aa0a93743197ecedbc65761650283d"
    end
  end

  def install
    bin.install "chapar-cli"
  end

  test do
    assert_match "chapar-cli v#{version}", shell_output("#{bin}/chapar-cli version")
  end
end
