# Generated by build/homebrew/render-formula.sh when a release is published;
# edit the template in chapar-rest/chapar, not this file.
class ChaparCli < Formula
  desc "Run Chapar API test cases from the command-line"
  homepage "https://github.com/chapar-rest/chapar"
  version "0.9.1"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.1/chapar-cli-macos-v0.9.1-arm64.tar.gz"
      sha256 "0f59b93afa5983baf711e60fcaa983ccdaa4fa1a6d65628eb8628deeed93b130"
    end
    on_intel do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.1/chapar-cli-macos-v0.9.1-amd64.tar.gz"
      sha256 "1cf87e6c8aed8ad46e0a1e484c11d4db96cf5a316bdac7f9b2bb4069d1cf543a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.1/chapar-cli-linux-v0.9.1-arm64.tar.gz"
      sha256 "a14c7f4b6a0f4859d30d2c0495fc415ccd0f1d2c1673a358479fd2de3ef12b45"
    end
    on_intel do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.9.1/chapar-cli-linux-v0.9.1-amd64.tar.gz"
      sha256 "b14355283545a07c7e594c278716a870f5190b5da495849e4b5187689a314f64"
    end
  end

  def install
    bin.install "chapar-cli"
  end

  test do
    assert_match "chapar-cli v#{version}", shell_output("#{bin}/chapar-cli version")
  end
end
