# Generated by build/homebrew/render-formula.sh when a release is published;
# edit the template in chapar-rest/chapar, not this file.
class ChaparCli < Formula
  desc "Run Chapar API test cases from the command-line"
  homepage "https://github.com/chapar-rest/chapar"
  version "0.8.0"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.8.0/chapar-cli-macos-v0.8.0-arm64.tar.gz"
      sha256 "0fa33b61900e0db5ad95c7cb0c3fd2e139ad23e57329f89411ce8885e15b6100"
    end
    on_intel do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.8.0/chapar-cli-macos-v0.8.0-amd64.tar.gz"
      sha256 "935316ede9ab4e1ee784388a9a607841fc660dd061df9ecfd7371fc2e61b83fe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.8.0/chapar-cli-linux-v0.8.0-arm64.tar.gz"
      sha256 "3c6b6ba6ed79540aabc12c86b811d79dbfb09b3e0c6dc66f4732cc1db10ad812"
    end
    on_intel do
      url "https://github.com/chapar-rest/chapar/releases/download/v0.8.0/chapar-cli-linux-v0.8.0-amd64.tar.gz"
      sha256 "06c9484f8d1a994712f8c37144b49d70682f5c9b470c7aa96d97f5ee6b6838ff"
    end
  end

  def install
    bin.install "chapar-cli"
  end

  test do
    assert_match "chapar-cli v#{version}", shell_output("#{bin}/chapar-cli version")
  end
end
